project:
  type: website

website:
  title: "Stats & R"
  favicon: Stats-&-R.png
  page-navigation: true
  navbar:
    logo: Stats-&-R.png
    logo-alt: "Stats-&-R.png"
    left:
      - text: "About"
        menu:
          - Who.qmd
      - text: "Works"
        menu: 
          - Datavisualization.qmd
      - text: "R Graph"
        menu: 
          - Graph.qmd
    pinned: true
    search: true
    
format:
  html:
    code-fold: false
    code-summary: "show the code"
    code-overflow: scroll
    code-line-numbers: true
    toc: true
    toc-title: Contents
    toc-location: left
    number-sections: false
    html-math-method: katex
    theme:
       - superhero
       - superhero.scss
    highlight-style: arrow-dark
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    comments:
      hypothesis:
        theme: clean
        
    css: styles.css
editor: visual