project:
  type: website

website:
  google-analytics: 
    tracking-id: "G-Y96LK2RNJD"
    anonymize-ip: true
  title: "Stats & R"
  favicon: Stats-&-R.png
  site-url: https://stats-r.com/
  description: "This is NING LI's personal website about Data Sciennce by R and Python programming language." 
  page-navigation: true
  page-footer: 
    left:  "©2023 Stats & R made with ❤️ and [Quarto](https://quarto.org/), by [NING](about.qmd). License: [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right:
      - icon: envelope
        href: mailto:ln729500172@gmail.com
      - icon: twitter
        href: https://twitter.com/ningli3739
      - icon: github
        href: https://github.com/NING3739
  navbar:
    logo: Stats-&-R.png
    logo-alt: "Stats-&-R.png"
    left:
      - text: "Posts"
        href: posts.qmd
      - text: "About"
        href: about.qmd
      - text: "Series"
        href: series.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: envelope
        href: mailto:ln729500172@gmail.com
      - icon: twitter
        href: https://twitter.com/ningli3739
      - icon: github
        href: https://github.com/NING3739
    pinned: true
    search: true

format:
  html:
    anchor-sections: true
    citations-hover: true
    code-fold: true
    code-summary: "show the code"
    code-overflow: scroll
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    css: styles.css
    fig-align: center
    fig-cap-location: top
    footnotes-hover: true
    link-external-newwindow: true
    highlight-style: github
    html-math-method: katex
    smooth-scroll: true
    theme: Litera
    toc: true
    toc-title: Contents
    toc-location: left
    
editor: visual