project:
  type: website
  
  
website:
  description: "Welcome to Stats & R. This is a personal website devoted primarily to R, Python, and statistics."
  favicon: Stats-&-R.png
  google-analytics: 
    anonymize-ip: true
    tracking-id: "G-Y96LK2RNJD"
  page-navigation: true
  repo-actions: [edit, issue]
  repo-url: https://github.com/NING3739/statsr
  site-url: https://stats-r.com/
  title: "Stats & R"
  
  
  navbar:
    background: "#A7D5E8" 
    logo: Stats-&-R.png
    logo-alt: "Stats-&-R.png"
    pinned: true
    search: true
    
    left:
      - text: "Posts"
        href: posts.qmd
      - text: "About"
        href: about.qmd
      - text: "Series"
        href: series.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: envelope
        href: mailto:ln729500172@gmail.com
      - icon: twitter
        href: https://twitter.com/ningli3739
      - icon: github
        href: https://github.com/NING3739
        
        
  page-footer:
    background: "#A7D5E8"
    left:  "©2023 Stats & R made with ❤️ and [Quarto](https://quarto.org/), by [NING](about.qmd). License: [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right:
      - icon: envelope
        href: mailto:ln729500172@gmail.com
      - icon: twitter
        href: https://twitter.com/ningli3739
      - icon: github
        href: https://github.com/NING3739


format:
  html:
    anchor-sections: true
    citations-hover: true
    code-fold: true
    code-summary: "show the code"
    code-overflow: scroll
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    css: styles.css
    fig-align: center
    fig-cap-location: top
    footnotes-hover: true
    highlight-style: github
    html-math-method: katex
    link-external-newwindow: true
    smooth-scroll: true
    theme: Litera
    toc: true
    toc-title: Contents
    toc-location: left


freeze: auto
    

editor: visual