project:
  type: website
website:
  cookie-consent: 
    type: express
    style: headline
    palette: dark
  google-analytics: 
    tracking-id: "G-Y96LK2RNJD"
    anonymize-ip: true
  title: "Stats & R"
  favicon: Stats-&-R.png
  page-navigation: true
  page-footer: 
    left:  "© 2022 Stats & R™ made with❤️ by [NING](Who.qmd)"
    right:
      - icon: envelope
        href: mailto:ln729500172@gmail.com
      - icon: twitter
        href: https://twitter.com/ningli3739
      - icon: github
        href: https://github.com/NING3739
  navbar:
    logo: Stats-&-R.png
    logo-alt: "Stats-&-R.png"
    logo-href: index.qmd
    left:
      - href: "Blog.qmd"
        text: "Blog"
      - href: "who.qmd"
        text: "About"
      - text: "Works"
        menu: 
          - Datavisualization.qmd
      - href: Contact.qmd
        text: "Contact"
    right:
      - icon: envelope
        href: mailto:ln729500172@gmail.com
      - icon: twitter
        href: https://twitter.com/ningli3739
      - icon: github
        href: https://github.com/NING3739
    pinned: true
    search: true
    
    
format:
  html:
    code-fold: true
    code-summary: "show the code"
    code-overflow: scroll
    code-line-numbers: true
    toc: true
    toc-title: Contents
    toc-location: left
    html-math-method: katex
    theme: Litera
       #- superhero
       #- superhero.scss
    highlight-style: arrow-light
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    comments:
      hypothesis:
        theme: clean
    css: styles.css
editor: visual